### ISSUE TITLE
ImageProvider - OOm

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#187]
```05-16 12:58:18.769  20691-20691/? E/dalvikvm-heap﹕ Out of memory on a 8294416-byte allocation.
05-16 12:58:18.769  20691-20691/? I/dalvikvm﹕ "main" prio=5 tid=1 RUNNABLE
05-16 12:58:18.769  20691-20691/? I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x40d6d538 self=0x40d5d6c8
05-16 12:58:18.769  20691-20691/? I/dalvikvm﹕ | sysTid=20691 nice=-19 sched=0/0 cgrp=default handle=1074450224
05-16 12:58:18.769  20691-20691/? I/dalvikvm﹕ | schedstat=( 0 0 0 ) utm=132 stm=19 core=0
05-16 12:58:18.769  20691-20691/? I/dalvikvm﹕ at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
05-16 12:58:18.769  20691-20691/? I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:663)
05-16 12:58:18.769  20691-20691/? I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:392)
05-16 12:58:18.769  20691-20691/? I/dalvikvm﹕ at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:457)
05-16 12:58:18.779  20691-20691/? I/dalvikvm﹕ at android.graphics.drawable.Drawable.createFromPath(Drawable.java:930)
05-16 12:58:18.779  20691-20691/? I/dalvikvm﹕ at com.pcinpact.datastorage.ImageProvider.getDrawable(ImageProvider.java:143)
05-16 12:58:18.779  20691-20691/? I/dalvikvm﹕ at android.text.HtmlToSpannedConverter.startImg(Html.java:629)
05-16 12:58:18.779  20691-20691/? I/dalvikvm﹕ at android.text.HtmlToSpannedConverter.handleStartTag(Html.java:513)
05-16 12:58:18.779  20691-20691/? I/dalvikvm﹕ at android.text.HtmlToSpannedConverter.startElement(Html.java:756)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at org.ccil.cowan.tagsoup.Parser.stagc(Parser.java:1016)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:565)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.text.HtmlToSpannedConverter.convert(Html.java:435)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.text.Html.fromHtml(Html.java:138)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at com.pcinpact.adapters.ItemsAdapter.getView(ItemsAdapter.java:317)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.widget.AbsListView.obtainView(AbsListView.java:2472)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.widget.ListView.makeAndAddView(ListView.java:1776)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.widget.ListView.fillDown(ListView.java:678)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.widget.ListView.fillFromTop(ListView.java:739)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.widget.ListView.layoutChildren(ListView.java:1629)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.widget.AbsListView.onLayout(AbsListView.java:2307)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.view.View.layout(View.java:14124)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.view.ViewGroup.layout(ViewGroup.java:4660)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.view.View.layout(View.java:14124)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.view.ViewGroup.layout(ViewGroup.java:4660)
05-16 12:58:18.789  20691-20691/? I/dalvikvm﹕ at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.View.layout(View.java:14124)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.ViewGroup.layout(ViewGroup.java:4660)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.View.layout(View.java:14124)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.ViewGroup.layout(ViewGroup.java:4660)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.View.layout(View.java:14124)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.ViewGroup.layout(ViewGroup.java:4660)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2029)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1850)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1143)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4684)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.Choreographer.doCallbacks(Choreographer.java:555)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.Choreographer.doFrame(Choreographer.java:525)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.os.Handler.handleCallback(Handler.java:615)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.os.Handler.dispatchMessage(Handler.java:92)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.os.Looper.loop(Looper.java:177)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at android.app.ActivityThread.main(ActivityThread.java:4947)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at java.lang.reflect.Method.invokeNative(Native Method)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at java.lang.reflect.Method.invoke(Method.java:511)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ at dalvik.system.NativeStart.main(Native Method)
05-16 12:58:18.799  20691-20691/? I/dalvikvm﹕ [ 05-16 12:58:18.799 20691:20691 D/skia     ]
    --- decoder->decode returned false
05-16 12:58:18.799  20691-20691/? W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40d6c2d0)
05-16 12:58:18.809  20691-20691/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:663)
            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:392)
            at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:457)
            at android.graphics.drawable.Drawable.createFromPath(Drawable.java:930)
            at com.pcinpact.datastorage.ImageProvider.getDrawable(ImageProvider.java:143)
            at android.text.HtmlToSpannedConverter.startImg(Html.java:629)
            at android.text.HtmlToSpannedConverter.handleStartTag(Html.java:513)
            at android.text.HtmlToSpannedConverter.startElement(Html.java:756)
            at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
            at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
            at org.ccil.cowan.tagsoup.Parser.stagc(Parser.java:1016)
            at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:565)
            at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
            at android.text.HtmlToSpannedConverter.convert(Html.java:435)
            at android.text.Html.fromHtml(Html.java:138)
            at com.pcinpact.adapters.ItemsAdapter.getView(ItemsAdapter.java:317)
            at android.widget.AbsListView.obtainView(AbsListView.java:2472)
            at android.widget.ListView.makeAndAddView(ListView.java:1776)
            at android.widget.ListView.fillDown(ListView.java:678)
            at android.widget.ListView.fillFromTop(ListView.java:739)
            at android.widget.ListView.layoutChildren(ListView.java:1629)
            at android.widget.AbsListView.onLayout(AbsListView.java:2307)
            at android.view.View.layout(View.java:14124)
            at android.view.ViewGroup.layout(ViewGroup.java:4660)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
            at android.view.View.layout(View.java:14124)
            at android.view.ViewGroup.layout(ViewGroup.java:4660)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14124)
            at android.view.ViewGroup.layout(ViewGroup.java:4660)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
            at android.view.View.layout(View.java:14124)
            at android.view.ViewGroup.layout(ViewGroup.java:4660)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
            at android.view.View.layout(View.java:14124)
            at android.view.ViewGroup.layout(ViewGroup.java:4660)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2029)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1850)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1143)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4684)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
            at android.view.Choreographer.doCallbacks(Choreographer.java:555)
            at android.view.Choreographer.doFrame(Choreographer.java:525)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:177)
            at android.app.ActivityThread.main(ActivityThread.java:4947)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
            at dalvik.system.NativeStart.main(Native Method)
05-16 12:58:18.890    1726-1746/? E/android.os.Debug﹕ !@Dumpstate > dumpstate -k -t -z -d -o /data/log/dumpstate_app_error```

**Comment by AnaelMobilia** [comment]
http://developer.android.com/training/displaying-bitmaps/index.html

**Comment by AnaelMobilia** [comment]
Suite à tests, pas intéressant : lenteurs++
Vu le peu de crash sur ce point là (systématiquement sur ma tablette...) + le fait que ça ne se produit plus dans les dernières releases

=> fermeture du ticket.
