### ISSUE TITLE
Commentaires - liens clickables

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#188]
Ne fonctionne plus.
Voir #81

**Comment by AnaelMobilia** [comment]
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens: onTouchEvent()
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.app.ContextImpl.startActivity(ContextImpl.java:1244)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.app.ContextImpl.startActivity(ContextImpl.java:1231)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:291)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.text.style.URLSpan.onClick(URLSpan.java:62)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:212)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at com.pcinpact.adapters.GestionLiens.onTouchEvent(GestionLiens.java:41)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.widget.TextView.onTouchEvent(TextView.java:8402)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.View.dispatchTouchEvent(View.java:7485)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2273)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2010)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2273)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2010)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2273)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2010)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2273)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2010)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2273)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2010)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2273)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2010)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2239)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1534)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.app.Activity.dispatchTouchEvent(Activity.java:2466)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.dispatchTouchEvent(ActionBarActivityDelegateICS.java:268)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2187)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.View.dispatchPointerEvent(View.java:7665)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3813)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3697)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4935)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4914)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5012)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.os.MessageQueue.nativePollOnce(Native Method)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.os.MessageQueue.next(MessageQueue.java:125)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.os.Looper.loop(Looper.java:124)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at android.app.ActivityThread.main(ActivityThread.java:5306)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at java.lang.reflect.Method.invokeNative(Native Method)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at java.lang.reflect.Method.invoke(Method.java:511)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
10-12 21:58:56.245 15055-15055/com.pcinpact E/GestionLiens:     at dalvik.system.NativeStart.main(Native Method)
