### ISSUE TITLE
Erreur avec https://cdn....

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#192]
Erreur avec https://cdn.... : images en erreur et non téléchargées

**Comment by AnaelMobilia** [comment]
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader: download() - Erreur pour https://cdn.nextinpact.com/images/bd/news/mini-156636.jpeg
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader: javax.net.ssl.SSLPeerUnverifiedException: Cannot verify hostname: cdn.nextinpact.com
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at android.net.SSLCertificateSocketFactory.verifyHostname(SSLCertificateSocketFactory.java:214)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:353)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:382)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at android.net.http.AndroidHttpClient.execute(AndroidHttpClient.java:257)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at com.pcinpact.network.Downloader.download(Downloader.java:91)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at com.pcinpact.network.Downloader.download(Downloader.java:57)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at com.pcinpact.network.AsyncImageDownloader.doInBackground(AsyncImageDownloader.java:84)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at com.pcinpact.network.AsyncImageDownloader.doInBackground(AsyncImageDownloader.java:38)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-12 20:01:57.864 3563-3669/com.pcinpact E/Downloader:     at java.lang.Thread.run(Thread.java:856)
