### ISSUE TITLE
Crash / ThreadPoolExecutor

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#200]
06-21 16:44:21.447 2457-2457/com.pcinpact I/AsyncImageDownloader: AsyncImageDownloader()https://cdn2.nextinpact.com/images/bd/square-linked-media/12149.jpg
06-21 16:44:21.447 2457-2457/com.pcinpact E/AsyncHTMLDownloader: onPostExecute()
                                                                 java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@26bfa5d0 rejected from java.util.concurrent.ThreadPoolExecutor@31c6a2fa[Running, pool size = 5, active threads = 5, queued tasks = 128, completed tasks = 58]
                                                                     at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
                                                                     at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                     at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                     at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:594)
                                                                     at com.pcinpact.datastorage.ImageProvider.telechargerImage(ImageProvider.java:267)
                                                                     at com.pcinpact.ListeArticlesActivity.telechargeArticles(ListeArticlesActivity.java:524)
                                                                     at com.pcinpact.ListeArticlesActivity.downloadHTMLFini(ListeArticlesActivity.java:536)
                                                                     at com.pcinpact.network.AsyncHTMLDownloader.onPostExecute(AsyncHTMLDownloader.java:282)
                                                                     at com.pcinpact.network.AsyncHTMLDownloader.onPostExecute(AsyncHTMLDownloader.java:42)
                                                                     at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                     at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by AnaelMobilia** [comment]
Optimisation en cas de crash déjà faite.
Difficile de prévoir la limite (système) et l'état de charge de la queue.
En cas de soucis, pas de blocage des compteurs de DL. Sera DL au prochain refresh.
