### ISSUE TITLE
crash 2.1.0 / Drawable null

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#203]
Crash de manière aléatoire dans tests google

 FATAL EXCEPTION: main
 Process: com.pcinpact, PID: 26771
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference
 	at com.pcinpact.datastorage.ImageProvider.gestionTaille(ImageProvider.java:198)
 	at com.pcinpact.datastorage.ImageProvider.getDrawable(ImageProvider.java:143)
 	at android.text.HtmlToSpannedConverter.startImg(Html.java:634)
 	at android.text.HtmlToSpannedConverter.handleStartTag(Html.java:520)
 	at android.text.HtmlToSpannedConverter.startElement(Html.java:761)
 	at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
 	at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
 	at org.ccil.cowan.tagsoup.Parser.stagc(Parser.java:1016)
 	at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:624)
 	at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
 	at android.text.HtmlToSpannedConverter.convert(Html.java:442)
 	at android.text.Html.fromHtml(Html.java:136)
 	at com.pcinpact.datastorage.ImageProvider.downloadImageFini(ImageProvider.java:396)
 	at com.pcinpact.network.AsyncImageDownloader.onPostExecute(AsyncImageDownloader.java:140)
 	at com.pcinpact.network.AsyncImageDownloader.onPostExecute(AsyncImageDownloader.java:41)
 	at android.os.AsyncTask.finish(AsyncTask.java:636)
 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:135)
 	at android.app.ActivityThread.main(ActivityThread.java:5254)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by AnaelMobilia** [comment]
Pas de précisions sur la cause précises : article crashe sur vidéo démo, une seule fois en dev.
