### ISSUE TITLE
Téléchargement images crash

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#214]
10-02 01:08:04.689 18870-8241/com.pcinpact E/XXX: START https://cdn2.nextinpact.com/images/bd/square-linked-media/13651.jpg
10-02 01:08:04.691 18870-8241/com.pcinpact E/Downloader: download() - timeout : 0
10-02 01:12:19.368 18870-8241/com.pcinpact E/Downloader: download() - Erreur de téléchargement pour https://cdn2.nextinpact.com/images/bd/square-linked-media/13651.jpg
                                                         java.net.HttpRetryException: Cannot retry due to connection time
                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:394)
                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:510)
                                                             at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                                             at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
                                                             at com.pcinpact.network.Downloader$override.download(Downloader.java:107)
                                                             at com.pcinpact.network.Downloader$override.access$dispatch(Downloader.java)
                                                             at com.pcinpact.network.Downloader.download(Downloader.java:0)
                                                             at com.pcinpact.network.AsyncImageDownloader.doInBackground(AsyncImageDownloader.java:90)
                                                             at com.pcinpact.network.AsyncImageDownloader.doInBackground(AsyncImageDownloader.java:41)
                                                             at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                             at java.lang.Thread.run(Thread.java:818)
10-02 01:12:19.383 18870-8241/com.pcinpact E/XXX: END https://cdn2.nextinpact.com/images/bd/square-linked-media/13651.jpg

**Comment by AnaelMobilia** [comment]
Bug aléatoire avec des lenteurs de téléchargement par moment.
Non systématiquement reproductible

Pourrait être lié à HTTPS, mais pas d'amélioration si forçage URL images en HTTP.

**Comment by AnaelMobilia** [comment]
Ne se reproduit plus, uniquement sur version en développement.
Problème côté serveur / CDN ?
