### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/NextINpact-Unofficial#243]
05-02 22:54:27.273 27715-27715/com.pcinpact E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pcinpact, PID: 27715
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pcinpact/com.pcinpact.ArticleActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2581)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2647)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4352)
        at android.app.ActivityThread.-wrap15(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5763)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
        at com.pcinpact.adapters.ItemsAdapter.<init>(ItemsAdapter.java:88)
        at com.pcinpact.ArticleFragment.onCreateView(ArticleFragment.java:100)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
        at android.app.Activity.performStart(Activity.java:6296)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2544)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2647) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4352) 
        at android.app.ActivityThread.-wrap15(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1508) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5763) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by AnaelMobilia** [comment]
Plantage de l'application -> retour dans le fragment car en mode debug...
